### ISSUE TITLE
Keep getting an error on line 78 in domoticz.js

### ISSUE THREAD

**Issue by iMartien** [mjiderhamn/worx-landroid-nodejs#26]
Hi,

When the script is running and I open the Landroid App on my iPhone, it stops working with this error:

Landroid status: {"state":"Charging","errorMessage":null,"batteryPercentage":64,"totalMowingHours":122.6,"totalDistance":120211,"noOfAlarms":null}
/home/pi/worx-landroid-nodejs/domoticz.js:78
    "svalue": (typeof svalue != "undefined") ? svalue.toString() : ""
                                                     ^

TypeError: Cannot read property 'toString' of null
    at Domoticz.sendValue (/home/pi/worx-landroid-nodejs/domoticz.js:78:54)
    at Domoticz.setNoOfAlarms (/home/pi/worx-landroid-nodejs/domoticz.js:307:10)
    at LandroidCloud.updateListener (/home/pi/worx-landroid-nodejs/landroid-cloud2domoticz.js:62:14)
    at LandroidCloud.onMessage (/home/pi/worx-landroid-nodejs/landroid-cloud.js:244:12)
    at DeviceClient.<anonymous> (/home/pi/worx-landroid-nodejs/landroid-cloud.js:191:16)
    at emitThree (events.js:97:13)
    at DeviceClient.emit (events.js:175:7)
    at MqttClient.<anonymous> (/home/pi/worx-landroid-nodejs/node_modules/aws-iot-device-sdk/device/index.js:749:12)
    at emitThree (events.js:97:13)
    at MqttClient.emit (events.js:175:7)

**Comment by iMartien** [comment]
Found out that this only occurred when the mower is in "Charging" state... when it's mowing the problem does not occur...

**Comment by MagnusKlingenberg** [comment]
#27 May solve this problem but I dont have domotics so I cant test it out. @iMartien Please verify it and then it can be pushed to master

**Comment by iMartien** [comment]
Thanks @MagnusKlingenberg, It's running right now... did some testing with sending commands etc from the app, so far so good!

Will keep you posted.

**Comment by iMartien** [comment]
It has been running whole day today... Never done that before, so I think it is safe to say this is resolved now!

Thanks again @MagnusKlingenberg!
