### ISSUE TITLE
Domoticz + Landroid 2017 models

### ISSUE THREAD

**Issue by mjiderhamn** [mjiderhamn/worx-landroid-nodejs#7]

**Comment by hanspnyholm** [comment]
Missing a landroid-cloud2domotics application.

**Comment by mjiderhamn** [comment]
There is now a preview, without proper icon colours. @hanspnyholm and @Pastis67 , would you care to give it a try?

**Comment by Pastis67** [comment]
Hello
thank you :)
I got this error
C:\worx\landroid-cloud2domoticz.js:73
  var landroid = new Landroid(config);
                     ^

ReferenceError: Landroid is not defined
    at C:\worx\landroid-cloud2domoticz.js:73:22
    at Domoticz.createMissingDevices (C:\worx\domoticz.js:230:7)
    at Domoticz.createMissingDevices (C:\worx\domoticz.js:224:12)
    at Domoticz.createMissingDevices (C:\worx\domoticz.js:224:12)
    at Domoticz.createMissingDevices (C:\worx\domoticz.js:224:12)
    at Domoticz.createMissingDevices (C:\worx\domoticz.js:224:12)
    at Domoticz.createMissingDevices (C:\worx\domoticz.js:224:12)
    at C:\worx\domoticz.js:193:10
    at C:\worx\domoticz.js:166:7
    at C:\worx\domoticz.js:153:5
maybe I am doing something wrong :\

**Comment by olskar** [comment]
It seems to work fint connecting to domoticz, the state is not however shown
![skarmavbild 2017-07-17 kl 16 30 11](https://user-images.githubusercontent.com/18314560/28273052-85b19202-6b0d-11e7-8c36-e1485b978dde.png)

**Comment by mjiderhamn** [comment]
That line (73) should have been removed. Sorry about that. Could you try again?

**Comment by olskar** [comment]
On line 73  it should be LandroidCloud instead of Landroid in file
\landroid-cloud2domoticz.js:.

2017-07-17 16:11 GMT+02:00 Pastis67 <notifications@github.com>:

**Comment by olskar** [comment]
It seems to work fint connecting to domoticz, the state is not however
shown[image:
Infogad bild 1]

2017-07-17 15:03 GMT+02:00 Mattias Jiderhamn <notifications@github.com>:

**Comment by Pastis67** [comment]
It works here too :) thank you !!

**Comment by iz3man** [comment]
could you please go a bit more into detail how to make this work together with home-assistant?
i have HA and mosquitto running, but have no idea what to do with the .js files.
but even on a windows machine which would run the .bat file, no idea what calls what, and how the landroid sends the mqtt data to moquitto. or maybe just point me into the right direction. 
i really have no idea how .js files interact with HA.
thanks!

**Comment by iz3man** [comment]
no idea if this is the correct approach, but this is if i call it manually

```
root@hassbian:/home/worx-landroid-nodejs# nodejs landroid2home-assistant.js 
Scheduling polling
About to poll Landroid at http://Landroid for status

/home/worx-landroid-nodejs/node_modules/najax/lib/parse-options.js:6
    opts = Object.assign(opts, url)
                  ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at parseOptions (/home/worx-landroid-nodejs/node_modules/najax/lib/parse-options.js:6:19)
    at najax (/home/worx-landroid-nodejs/node_modules/najax/lib/najax.js:34:28)
    at Landroid.doPollStatus (/home/worx-landroid-nodejs/landroid.js:50:3)
    at Landroid.pollEvery (/home/worx-landroid-nodejs/landroid.js:160:8)
    at Object.<anonymous> (/home/worx-landroid-nodejs/landroid2home-assistant.js:13:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

```

**Comment by mjiderhamn** [comment]
@iz3man Looks like the version of najax I recently upgraded to is not compatible with your version of Node.JS. What version are you on (`node --version`)? Are you able to upgrade Node.JS?

**Comment by iz3man** [comment]
@mjiderhamn 
```
root@hassbian:/home/worx-landroid-nodejs# nodejs --version
v0.10.29
```

**Comment by mjiderhamn** [comment]
Wow, version [0.10.29 is three years old](https://nodejs.org/en/blog/release/v0.10.29/). You really should update. Have you tried something like `sudo apt-get update -y nodejs`?

**Comment by iz3man** [comment]
apt-get update doesn't take any options, but i installed another version of node. still this gives the same results.

```
root@hassbian:/home/worx-landroid-nodejs# node -v
v4.2.1
root@hassbian:/home/worx-landroid-nodejs# node landroid-cloud2home-assistant.js 
module.js:339
    throw err;
    ^

Error: Cannot find module 'aws-iot-device-sdk'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/worx-landroid-nodejs/landroid-cloud.js:6:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by iz3man** [comment]
i found that https://nodejs.org/dist/v8.1.4/node-v8.1.4-linux-arm64.tar.xz
would that be more appropriate?

**Comment by mjiderhamn** [comment]
@iz3man Did you run `npm install` after updating Node?

**Comment by olskar** [comment]
Have you run npm install in the folder to install dependencies?

On Jul 18, 2017 08:52, "iz3man" <notifications@github.com> wrote:

apt-get update doesn't take any options, but i installed another version of
node. still this gives the same results.

root@hassbian:/home/worx-landroid-nodejs# node -v
v4.2.1
root@hassbian:/home/worx-landroid-nodejs# node landroid-cloud2home-assistant.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'aws-iot-device-sdk'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/worx-landroid-nodejs/landroid-cloud.js:6:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/mjiderhamn/worx-landroid-nodejs/issues/7#issuecomment-315974507>,
or mute the thread

**Comment by iz3man** [comment]
sorry. my fault. after "npm install" it goes a good step forward, but still shows some error.

```
root@hassbian:/home/worx-landroid-nodejs# node landroid-cloud2home-assistant.js 
UUID: 3e3ae630-6bcb-11e7-9e12-57c4b018XXXX
Downloaded guest token
API token set to qiJNz3waS4I99FPvTaPt2C2R46WXXXXX
Logged in as XXXXXX@XXXX.net - user token retrieved from API
API token set to g1O1apUCAes38czPvsdk7Xd4bhTkwRAv
Certificate retrieved
/home/worx-landroid-nodejs/landroid-cloud.js:116
      self.setCertificate(Buffer.from(data.pkcs12, 'base64'));
                                 ^

TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at /home/worx-landroid-nodejs/landroid-cloud.js:116:34
    at Object.najax.success (/home/worx-landroid-nodejs/landroid-cloud.js:248:9)
    at fire (/home/worx-landroid-nodejs/node_modules/najax/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.self.fireWith (/home/worx-landroid-nodejs/node_modules/najax/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.self.fire [as resolve] (/home/worx-landroid-nodejs/node_modules/najax/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at dataHandler (/home/worx-landroid-nodejs/node_modules/najax/lib/najax.js:167:13)
    at IncomingMessage.<anonymous> (/home/worx-landroid-nodejs/node_modules/najax/lib/najax.js:198:9)
    at emitNone (events.js:72:20)

```
(personal data greyed out on purpose)

**Comment by mjiderhamn** [comment]
`Buffer` [changed significantly in Node.JS 6.0](https://nodejs.org/dist/v6.0.0/docs/api/buffer.html#buffer_new_buffer_str_encoding). I made [a change](https://github.com/mjiderhamn/worx-landroid-nodejs/commit/f1b4252a79966d1c2b4d14ceb24097e864b79993) to `landroid-cloud.js` to make it compatible with older versions. @iz3man , could you give it another try with the latest update of this project?

**Comment by iz3man** [comment]
thanks @mjiderhamn. fyi: this fix didn't help, and threw some other error messages. but i chose a different way. i dl'd https://nodejs.org/dist/v8.1.4/node-v8.1.4-linux-armv6l.tar.xz (ARM for Rpi) and now it seems to work :)

```
root@hassbian:/home/worx-landroid-nodejs# node landroid-cloud2home-assistant.js 
UUID: 0fa38a20-6c57-11e7-bf0b-1d1275
Downloaded guest token
API token set to qiJNz3waS4I99FPvTaPt2C2R46
Logged in as xxx@xxx.net - user token retrieved from API
API token set to g1O1apUCAes38czPvsdk7Xd4b
Certificate retrieved
Fetching root CA
Connecting to MQTT broker
Connected to MQTT broker - subscribing to DB510/F0FE6B415A90/commandOut
```

now that i'm that far, we'll see how i get mqtt data processed into HA?!

**Comment by iz3man** [comment]
seems to work somehow, but i can't make any sense out of this:

```
Certificate retrieved
Fetching root CA
Connecting to MQTT broker
Connected to MQTT broker - subscribing to DB510/F0FE6B4xxxx/commandOut
Landroid status: {"state":"Rain delay","errorMessage":null,"batteryPercentage":null,"totalMowingHours":18.1,"noOfAlarms":null}
Error calling Home Assistant: {"readyState":0,"status":0,"statusText":"error"}
Error calling Home Assistant: {"readyState":0,"status":0,"statusText":"error"}
Error calling Home Assistant: {"readyState":0,"status":0,"statusText":"error"}
```

**Comment by iz3man** [comment]
btw: in config.js, the variable:  "homeAssistantPassword:" is the webfrontend password, correct?

**Comment by mjiderhamn** [comment]
@iz3man Mosquitto is not involved. See [here](https://home-assistant.io/developers/rest_api/) for what Home Assistant password to set.

What error did you get before updating Node? I'm interested if there are other compatibility issues to be looked at.

**Comment by iz3man** [comment]
i'll see if i can reproduce it. but could you please tell me what
`Error calling Home Assistant: {"readyState":0,"status":0,"statusText":"error"}` 
means, and how to use the mqtt data if not with mosquitto? i thought mosquitto was the broker for it?!

**Comment by iz3man** [comment]
here's the output with the "old" node binary:

```
root@hassbian:/home/worx-landroid-nodejs# /usr/local/bin/node.bak landroid-cloud2home-assistant.js
UUID: a7b66420-6cb8-11e7-b560-3d6f6a53b9aa
Downloaded guest token
API token set to qiJNz3waS4I99FPvTaPt2C2R4xxxxxx
Logged in as xxxxxx - user token retrieved from API
API token set to g1O1apUCAes38czPvsdk7xxxxxxx
Certificate retrieved
/home/worx-landroid-nodejs/landroid-cloud.js:118
        decoded = Buffer.from(data.pkcs12, 'base64');
                         ^

TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at /home/worx-landroid-nodejs/landroid-cloud.js:118:26
    at Object.najax.success (/home/worx-landroid-nodejs/landroid-cloud.js:254:9)
    at fire (/home/worx-landroid-nodejs/node_modules/najax/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.self.fireWith (/home/worx-landroid-nodejs/node_modules/najax/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.self.fire [as resolve] (/home/worx-landroid-nodejs/node_modules/najax/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at dataHandler (/home/worx-landroid-nodejs/node_modules/najax/lib/najax.js:167:13)
    at IncomingMessage.<anonymous> (/home/worx-landroid-nodejs/node_modules/najax/lib/najax.js:198:9)
    at emitNone (events.js:72:20)
```

**Comment by mjiderhamn** [comment]
`Error calling Home Assistant` means there was a problem calling the Home Assistant REST API. Wrong IP address or wrong password are two possible reasons.

The Landroid sends information (and fetches commands) from an MQTT broker at Amazon Web Services, AWS. (It is supposedly not Mosquitto.) My Node.JS script subscribes to that MQTT topic, and sends the information to Home Assistant via HAs REST API.

You only need to set up Mosquitto if you plan to use Domoticz (which this issue is about, BTW), since Domoticz does not have an API.

**Comment by iz3man** [comment]
thanks @mjiderhamn. it WAS a problem with user/pwd. somehow. it was the HA's url. fixed that, and **now it's working**. at least a little.
all info i got is:
`Landroid status: {"state":"Home","errorMessage":"Unknown error","batteryPercentage":null,"totalMowingHours":20.7,"noOfAlarms":1}`

my app shows that it's home. no error at all. and no idea what the alarms mean.
but i can't see battery state at all, no charging state, no voltage.

but so far: amazing work! really appreciated. thank you.
